#!/bin/sh

rm -rf indexDir materialization_lubm1

# load the database in the ttl directory, creating the index in "indexDir".
echo "========================"
../vlog load -f ttl -i indexDir 2>&1
echo "========================"

#materialize using the LUBM1_LE rules and store the result in "materialization_lubm1".
echo "========================"
../vlog mat -i indexDir --storemat materialization_lubm1 --decompressmat 1 --rules dlog/LUBM1_LE.dlog 2>&1
echo "========================"
