/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vlog_cplusplus_VLog */

#ifndef _Included_vlog_cplusplus_VLog
#define _Included_vlog_cplusplus_VLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vlog_cplusplus_VLog
 * Method:    start
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vlog_cplusplus_VLog_start
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
